version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install pytest
      - pip install flask
  pre_build:
    commands:
      - echo Running pre-build steps...
      - pytest --version
  build:
    commands:
      - echo Running build steps...
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
